# vi: sw=2 ts=2 sts=2 expandtab
language: python
sudo: false

os:
  - linux
  - osx

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"  # swig doesn't seem to work :(

dist: trusty

matrix:
  fast_finish: true
  allow_failures:
    - os: osx

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --remove channels defaults
  - conda config --add channels 'conda-forge'

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION swig pytest coverage coveralls
  - conda activate test-environment

  - python setup.py build
  - python setup.py install

script: 
  - pytest -vv library/Box2D/tests/

after_success:
  - coveralls
